# Ryan Tool
## Week 10 - 03/26/2021
### Python NumPy Array Processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [6]:
print(my_arr.dtype)

int32


In [7]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']

my_strArr = np.array(fruits)

In [8]:
print(my_strArr.dtype)

<U6


In [9]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [10]:
print(my_arr2.dtype)

|S2


In [11]:
my_arr2 = np.array([1,2,3,4,5], dtype='S')

print(my_arr2.dtype)

|S1


In [12]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

In [13]:
print(my_arr3.dtype)

int32


In [14]:
myErrarr = np.array(['1','2','3','4','5'], dtype='i')

In [15]:
print(myErrarr)

[1 2 3 4 5]


In [16]:
my_arr = np.array(['1','2','c','4','5'], dtype='i')

ValueError: invalid literal for int() with base 10: 'c'

In [19]:
scores = [78.5, 88.9, 90.3, 89.9]

my_arr = np.array(scores)

In [20]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [21]:
arr = my_arr.astype('i')

In [22]:
print(arr)

[78 88 90 89]


In [23]:
arr = np.array([1,0,0,3,4,5,6,7,0])

In [24]:
print(arr.dtype)

int32


In [25]:
bool_arr = arr.astype(bool)

In [27]:
print(arr)
print(bool_arr)

[1 0 0 3 4 5 6 7 0]
[ True False False  True  True  True  True  True False]


In [28]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [29]:
#Numpy built-in functions to generate arrays from existing arrays
#copy and view
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [30]:
arr[3] = 4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [34]:
my_list = [11,12,13,14,15]

arr = np.array(my_list)
v_arr = arr.view()

print(arr)
print(v_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [35]:
arr[3] = 4
print(arr)
print(v_arr)

[11 12 13  4 15]
[11 12 13  4 15]


In [36]:
v_arr[2] = 3
print(arr)
print(v_arr)

[11 12  3  4 15]
[11 12  3  4 15]


In [37]:
print(c_arr.base)
print(v_arr.base)

[11 12 13  4 15]
[11 12  3  4 15]


In [38]:
#Shape gives number of elements in each dimension

In [40]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
my_arr.shape

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


(2, 5)

In [41]:
#Shape returns 2 dimensions and each dimension has 5 elements


In [43]:
arr = np.array(lst1,ndmin=4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [44]:
arr = np.array(lst1,ndmin=6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [ ]:
#each index in the shape tells the number of elements in that dimension