# Ryan Tool
## Week 11 - 04/02/2021
### Python NumPy Universal Functions

In [3]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]
arr2 = [11,12,13,14,15,16,17,18,19]
z = []

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [5]:
#zip
fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Cark", "Robert")

flname = zip(fname, lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Cark'), ('Christy', 'Robert'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [7]:
arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr1 = np.random.randn(10)
arr1

array([ 0.27069099,  0.16945359,  0.54699419, -0.20515907, -1.28399608,
       -0.48290627,  1.42746338, -1.23857119,  0.28615987,  0.10549541])

In [13]:
arr2 = np.random.randn(10)
arr2

array([-1.32616044, -0.01154277,  0.35491148, -0.96508465, -1.51305431,
        0.57173354,  0.57551283, -1.06611138,  0.57485284,  0.99063797])

In [14]:
np.add(arr1,arr2)

array([-1.05546945,  0.15791082,  0.90190567, -1.17024372, -2.79705039,
        0.08882727,  2.00297621, -2.30468257,  0.86101271,  1.09613338])

In [15]:
np.maximum(arr1,arr2)

array([ 0.27069099,  0.16945359,  0.54699419, -0.20515907, -1.28399608,
        0.57173354,  1.42746338, -1.06611138,  0.57485284,  0.99063797])

In [16]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [19]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [20]:
np.where((arr < 4) & (arr > 2), -1, -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, True, True, False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [23]:
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [27]:
#Using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])